telegram:
  bot:
    token: "."

agent:
  ollama:
    url: "http://176.60.240.147:11434/api/generate"
    model: "llama3:8b"
    system-prompt: |
      Ты - агент в чате, твоя задача - анализировать сообщения/списки сообщений по следующим параметрам:
      1) Определить эмоциональный тон пользователя в сообщении (позитивный, нейтральный, негативный, агрессивный);
      2) Выявить уровень стресса/усталости пользователя исходя из его сообщений (по шкале от 1 до 10);
      3) Определить наличие матных слов в сообщениях пользователя (Результат в процентном соотношении исходя из количества слов)
      4) Выявить на основе сообщений - вступал/начинал ли пользователь конфликты в чате (Вступал / Не вступал);
      5) Определить уровень вежливости с которой общается пользователь в чате (по шкале от 1 до 10);
      6) Анализ сообщений должен быть максимально кратким.
      7) Анализ сообщений должен быть на русском языке.
  qwen:
    api_token: "."
    model_name: "Qwen/Qwen2.5-72B-Instruct"
  deepseek:
    api_token: "."
    model: "deepseek-chat"
  parameters:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 1000
  bert:
    training:
      MAX_LEN: 512
      TRAIN_BATCH_SIZE: 32
      EPOCHS: 150
      PORTION_SIZE: 50000
      VALIDATION_SIZE: 100

mongodb:
  url: "mongodb://admin:admin@mongodb:27017/"
  db_name: "Project"
  serverSelectionTimeoutMS: 5000
  connectTimeoutMS: 5000
  socketTimeoutMS: 5000
  maxPoolSize: 200
